### ISSUE TITLE
Proposal for adding token balances to the dashboard

### ISSUE THREAD

**Issue by mishcheek** [scrtlabs/dash.scrt.network#61]
I would like to propose a new feature for the dashboard that would allow users to add tokens and see their token balances directly on the dashboard. Currently, users have to go to external apps/wallets to check their token balances, which can be time-consuming and inconvenient. With this new feature, users would be able to add their token wallets to the dashboard and see their token balances (possibly even LP balances) in real-time. This would provide a more seamless and user-friendly experience.

**Comment by kevinrieger** [comment]
Cool idea, currently on it!

<img width="1888" alt="Screenshot 2023-03-27 at 20 23 59" src="https://user-images.githubusercontent.com/26869062/228032406-432eb450-7db7-4dec-9526-a58e7732071a.png">

**Comment by kevinrieger** [comment]
Cool idea, currently on it!

<img width="1754" alt="Screenshot 2023-03-27 at 20 25 18" src="https://user-images.githubusercontent.com/26869062/228032631-025e0ef8-1e5d-42b0-981b-5622a482838f.png">

**Comment by kevinrieger** [comment]
It's live now! We're currently in the talks about adding a view for more assets here in the future, as well as adding a "Viewing Key Manager", where you can add viewing keys for all secret tokens available on Secret Network.
