### ISSUE TITLE
Initial fee grant does not transfer anything

### ISSUE THREAD

**Issue by tdiesler** [scrtlabs/dash.scrt.network#62]
I see "Fee Granted" and in mintscan I see it revoked again.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/244946/226078118-eb60d0e9-0f9d-4d14-9636-934bae8754cc.png">

Grant revocation should be reflected in the dashboard, otherwise it is confusing that a fee got granted but there is a 0 balance. Why would it be revoked? Should it be possible to get a new grant?

Also, the grant seems to be too small to do an initial unwrap of sSCRT

**Comment by SecretSaturn** [comment]
A initial fee grant is only valid for 1 day. To give out a new fee grant after 1 day, we first revoke the old fee grant (that's the revoke allowance) and then give out a new one. Looks like the new grant allowance transaction wasn't correctly included in a block, you didn't receive a new fee grant. Even if you do receive a fee grant, your SCRT balance will still be 0. A fee grant pays for your transactions with the balance from a different account, you don't directly get SCRT sent to your wallet.

The fee grant amount is enough to do an initial unwrap of sSCRT.
